pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh './mvnw -B -DskipTests clean package' 
            }
        }
    }
    post {
        always {
	        mail to: 'gmmr.mca007@gmail.com',
	             subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
	             body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}"
    	}
    }
}
